apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ccipwobac-python 
  janus-idp.io/tekton: ccipwobac-python
  backstage.io/kubernetes-id: ccipwobac-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ccipwobac-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  